// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "IMGroup-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // IMGroup
  //

  struct access::object_traits_impl< ::IMGroup, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::IMGroup, id_mysql >::id_type
  access::object_traits_impl< ::IMGroup, id_mysql >::
  id (const id_image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          ::tid_t,
          mysql::id_ulonglong >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::IMGroup, id_mysql >::id_type
  access::object_traits_impl< ::IMGroup, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          ::tid_t,
          mysql::id_ulonglong >::set_value (
        id,
        i.groupId_value,
        i.groupId_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::IMGroup, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // tid_
    //
    t[0UL] = 0;

    // groupId_
    //
    t[1UL] = 0;

    // creator_id_
    //
    t[2UL] = 0;

    // group_name_
    //
    if (t[3UL])
    {
      i.group_name_value.capacity (i.group_name_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::IMGroup, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // tid_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.tid_value;
    b[n].is_null = &i.tid_null;
    n++;

    // groupId_
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONGLONG;
      b[n].is_unsigned = 1;
      b[n].buffer = &i.groupId_value;
      b[n].is_null = &i.groupId_null;
      n++;
    }

    // creator_id_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.creator_id_value;
    b[n].is_null = &i.creator_id_null;
    n++;

    // group_name_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.group_name_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.group_name_value.capacity ());
    b[n].length = &i.group_name_size;
    b[n].is_null = &i.group_name_null;
    n++;
  }

  void access::object_traits_impl< ::IMGroup, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::IMGroup, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // tid_
    //
    {
      ::tid_t const& v =
        o.tid_;

      bool is_null (false);
      mysql::value_traits<
          ::tid_t,
          mysql::id_ulonglong >::set_image (
        i.tid_value, is_null, v);
      i.tid_null = is_null;
    }

    // groupId_
    //
    if (sk == statement_insert)
    {
      ::tid_t const& v =
        o.groupId_;

      bool is_null (false);
      mysql::value_traits<
          ::tid_t,
          mysql::id_ulonglong >::set_image (
        i.groupId_value, is_null, v);
      i.groupId_null = is_null;
    }

    // creator_id_
    //
    {
      ::tid_t const& v =
        o.creator_id_;

      bool is_null (false);
      mysql::value_traits<
          ::tid_t,
          mysql::id_ulonglong >::set_image (
        i.creator_id_value, is_null, v);
      i.creator_id_null = is_null;
    }

    // group_name_
    //
    {
      ::std::string const& v =
        o.group_name_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.group_name_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.group_name_value,
        size,
        is_null,
        v);
      i.group_name_null = is_null;
      i.group_name_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.group_name_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::IMGroup, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // tid_
    //
    {
      ::tid_t& v =
        o.tid_;

      mysql::value_traits<
          ::tid_t,
          mysql::id_ulonglong >::set_value (
        v,
        i.tid_value,
        i.tid_null);
    }

    // groupId_
    //
    {
      ::tid_t& v =
        o.groupId_;

      mysql::value_traits<
          ::tid_t,
          mysql::id_ulonglong >::set_value (
        v,
        i.groupId_value,
        i.groupId_null);
    }

    // creator_id_
    //
    {
      ::tid_t& v =
        o.creator_id_;

      mysql::value_traits<
          ::tid_t,
          mysql::id_ulonglong >::set_value (
        v,
        i.creator_id_value,
        i.creator_id_null);
    }

    // group_name_
    //
    {
      ::std::string& v =
        o.group_name_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.group_name_value,
        i.group_name_size,
        i.group_name_null);
    }
  }

  void access::object_traits_impl< ::IMGroup, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          ::tid_t,
          mysql::id_ulonglong >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::IMGroup, id_mysql >::persist_statement[] =
  "INSERT INTO `IMGroup` "
  "(`tid`, "
  "`groupId`, "
  "`creator_id`, "
  "`group_name`) "
  "VALUES "
  "(?, ?, ?, ?)";

  const char access::object_traits_impl< ::IMGroup, id_mysql >::find_statement[] =
  "SELECT "
  "`IMGroup`.`tid`, "
  "`IMGroup`.`groupId`, "
  "`IMGroup`.`creator_id`, "
  "`IMGroup`.`group_name` "
  "FROM `IMGroup` "
  "WHERE `IMGroup`.`groupId`=?";

  const char access::object_traits_impl< ::IMGroup, id_mysql >::update_statement[] =
  "UPDATE `IMGroup` "
  "SET "
  "`tid`=?, "
  "`creator_id`=?, "
  "`group_name`=? "
  "WHERE `groupId`=?";

  const char access::object_traits_impl< ::IMGroup, id_mysql >::erase_statement[] =
  "DELETE FROM `IMGroup` "
  "WHERE `groupId`=?";

  const char access::object_traits_impl< ::IMGroup, id_mysql >::query_statement[] =
  "SELECT "
  "`IMGroup`.`tid`, "
  "`IMGroup`.`groupId`, "
  "`IMGroup`.`creator_id`, "
  "`IMGroup`.`group_name` "
  "FROM `IMGroup`";

  const char access::object_traits_impl< ::IMGroup, id_mysql >::erase_query_statement[] =
  "DELETE FROM `IMGroup`";

  const char access::object_traits_impl< ::IMGroup, id_mysql >::table_name[] =
  "`IMGroup`";

  void access::object_traits_impl< ::IMGroup, id_mysql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.groupId_value = 0;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.groupId_ = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::IMGroup, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.groupId_);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::IMGroup, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (db);

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::IMGroup, id_mysql >::pointer_type
  access::object_traits_impl< ::IMGroup, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::IMGroup, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::IMGroup, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.groupId_);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::IMGroup, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::IMGroup, id_mysql >::object_type >
  access::object_traits_impl< ::IMGroup, id_mysql >::
  query (database&, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::IMGroup, id_mysql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS `IMGroup`");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE `IMGroup` (\n"
                      "  `tid` BIGINT UNSIGNED NOT NULL,\n"
                      "  `groupId` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,\n"
                      "  `creator_id` BIGINT UNSIGNED NOT NULL,\n"
                      "  `group_name` TEXT NOT NULL)\n"
                      " ENGINE=InnoDB");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_mysql,
    "IMGroup",
    &create_schema);
}

#include <odb/post.hxx>
