// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef IMMESSAGE_ODB_HXX
#define IMMESSAGE_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "IMMessage.hxx"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // IMMessage
  //
  template <>
  struct class_traits< ::IMMessage >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::IMMessage >
  {
    public:
    typedef ::IMMessage object_type;
    typedef ::IMMessage* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::tid_t id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // IMMessage
  //
  template <typename A>
  struct query_columns< ::IMMessage, id_mysql, A >
  {
    // tid
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::tid_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    tid_type_;

    static const tid_type_ tid;

    // relateId
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::tid_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    relateId_type_;

    static const relateId_type_ relateId;

    // fromId
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::tid_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    fromId_type_;

    static const fromId_type_ fromId;

    // toId
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::tid_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    toId_type_;

    static const toId_type_ toId;

    // createTime
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::ttime_t,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    createTime_type_;

    static const createTime_type_ createTime;

    // content
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    content_type_;

    static const content_type_ content;
  };

  template <typename A>
  const typename query_columns< ::IMMessage, id_mysql, A >::tid_type_
  query_columns< ::IMMessage, id_mysql, A >::
  tid (A::table_name, "`tid`", 0);

  template <typename A>
  const typename query_columns< ::IMMessage, id_mysql, A >::relateId_type_
  query_columns< ::IMMessage, id_mysql, A >::
  relateId (A::table_name, "`relateId`", 0);

  template <typename A>
  const typename query_columns< ::IMMessage, id_mysql, A >::fromId_type_
  query_columns< ::IMMessage, id_mysql, A >::
  fromId (A::table_name, "`fromId`", 0);

  template <typename A>
  const typename query_columns< ::IMMessage, id_mysql, A >::toId_type_
  query_columns< ::IMMessage, id_mysql, A >::
  toId (A::table_name, "`toId`", 0);

  template <typename A>
  const typename query_columns< ::IMMessage, id_mysql, A >::createTime_type_
  query_columns< ::IMMessage, id_mysql, A >::
  createTime (A::table_name, "`createTime`", 0);

  template <typename A>
  const typename query_columns< ::IMMessage, id_mysql, A >::content_type_
  query_columns< ::IMMessage, id_mysql, A >::
  content (A::table_name, "`content`", 0);

  template <typename A>
  struct pointer_query_columns< ::IMMessage, id_mysql, A >:
    query_columns< ::IMMessage, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::IMMessage, id_mysql >:
    public access::object_traits< ::IMMessage >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // tid_
      //
      unsigned long long tid_value;
      my_bool tid_null;

      // relateId_
      //
      unsigned long long relateId_value;
      my_bool relateId_null;

      // fromId_
      //
      unsigned long long fromId_value;
      my_bool fromId_null;

      // toId_
      //
      unsigned long long toId_value;
      my_bool toId_null;

      // createTime_
      //
      unsigned long long createTime_value;
      my_bool createTime_null;

      // content_
      //
      details::buffer content_value;
      unsigned long content_size;
      my_bool content_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 6UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::IMMessage, id_common >:
    public access::object_traits_impl< ::IMMessage, id_mysql >
  {
  };

  // IMMessage
  //
}

#include "IMMessage-odb.ixx"

#include <odb/post.hxx>

#endif // IMMESSAGE_ODB_HXX
