// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "User-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // User
  //

  struct access::object_traits_impl< ::User, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::User, id_mysql >::id_type
  access::object_traits_impl< ::User, id_mysql >::
  id (const id_image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          ::tid_t,
          mysql::id_ulonglong >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::User, id_mysql >::id_type
  access::object_traits_impl< ::User, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          ::tid_t,
          mysql::id_ulonglong >::set_value (
        id,
        i.tid_value,
        i.tid_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::User, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // tid_
    //
    t[0UL] = 0;

    // user_name_
    //
    if (t[1UL])
    {
      i.user_name_value.capacity (i.user_name_size);
      grew = true;
    }

    // user_passwd_
    //
    if (t[2UL])
    {
      i.user_passwd_value.capacity (i.user_passwd_size);
      grew = true;
    }

    // user_nickName_
    //
    if (t[3UL])
    {
      i.user_nickName_value.capacity (i.user_nickName_size);
      grew = true;
    }

    // faceType_
    //
    t[4UL] = 0;

    // customface_
    //
    if (t[5UL])
    {
      i.customface_value.capacity (i.customface_size);
      grew = true;
    }

    // customFaceFomt_
    //
    if (t[6UL])
    {
      i.customFaceFomt_value.capacity (i.customFaceFomt_size);
      grew = true;
    }

    // gender_
    //
    t[7UL] = 0;

    // birthday_
    //
    t[8UL] = 0;

    // signature_
    //
    if (t[9UL])
    {
      i.signature_value.capacity (i.signature_size);
      grew = true;
    }

    // address_
    //
    if (t[10UL])
    {
      i.address_value.capacity (i.address_size);
      grew = true;
    }

    // phoneNum_
    //
    if (t[11UL])
    {
      i.phoneNum_value.capacity (i.phoneNum_size);
      grew = true;
    }

    // email_
    //
    if (t[12UL])
    {
      i.email_value.capacity (i.email_size);
      grew = true;
    }

    // registTime_
    //
    t[13UL] = 0;

    // remark_
    //
    if (t[14UL])
    {
      i.remark_value.capacity (i.remark_size);
      grew = true;
    }

    // updateTime_
    //
    t[15UL] = 0;

    // teamInfo_
    //
    if (t[16UL])
    {
      i.teamInfo_value.capacity (i.teamInfo_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::User, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // tid_
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONGLONG;
      b[n].is_unsigned = 1;
      b[n].buffer = &i.tid_value;
      b[n].is_null = &i.tid_null;
      n++;
    }

    // user_name_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.user_name_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.user_name_value.capacity ());
    b[n].length = &i.user_name_size;
    b[n].is_null = &i.user_name_null;
    n++;

    // user_passwd_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.user_passwd_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.user_passwd_value.capacity ());
    b[n].length = &i.user_passwd_size;
    b[n].is_null = &i.user_passwd_null;
    n++;

    // user_nickName_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.user_nickName_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.user_nickName_value.capacity ());
    b[n].length = &i.user_nickName_size;
    b[n].is_null = &i.user_nickName_null;
    n++;

    // faceType_
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.faceType_value;
    b[n].is_null = &i.faceType_null;
    n++;

    // customface_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.customface_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.customface_value.capacity ());
    b[n].length = &i.customface_size;
    b[n].is_null = &i.customface_null;
    n++;

    // customFaceFomt_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.customFaceFomt_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.customFaceFomt_value.capacity ());
    b[n].length = &i.customFaceFomt_size;
    b[n].is_null = &i.customFaceFomt_null;
    n++;

    // gender_
    //
    b[n].buffer_type = MYSQL_TYPE_TINY;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.gender_value;
    b[n].is_null = &i.gender_null;
    n++;

    // birthday_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.birthday_value;
    b[n].is_null = &i.birthday_null;
    n++;

    // signature_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.signature_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.signature_value.capacity ());
    b[n].length = &i.signature_size;
    b[n].is_null = &i.signature_null;
    n++;

    // address_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.address_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.address_value.capacity ());
    b[n].length = &i.address_size;
    b[n].is_null = &i.address_null;
    n++;

    // phoneNum_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.phoneNum_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.phoneNum_value.capacity ());
    b[n].length = &i.phoneNum_size;
    b[n].is_null = &i.phoneNum_null;
    n++;

    // email_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.email_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.email_value.capacity ());
    b[n].length = &i.email_size;
    b[n].is_null = &i.email_null;
    n++;

    // registTime_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.registTime_value;
    b[n].is_null = &i.registTime_null;
    n++;

    // remark_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.remark_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.remark_value.capacity ());
    b[n].length = &i.remark_size;
    b[n].is_null = &i.remark_null;
    n++;

    // updateTime_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.updateTime_value;
    b[n].is_null = &i.updateTime_null;
    n++;

    // teamInfo_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.teamInfo_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.teamInfo_value.capacity ());
    b[n].length = &i.teamInfo_size;
    b[n].is_null = &i.teamInfo_null;
    n++;
  }

  void access::object_traits_impl< ::User, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::User, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // tid_
    //
    if (sk == statement_insert)
    {
      ::tid_t const& v =
        o.tid_;

      bool is_null (false);
      mysql::value_traits<
          ::tid_t,
          mysql::id_ulonglong >::set_image (
        i.tid_value, is_null, v);
      i.tid_null = is_null;
    }

    // user_name_
    //
    {
      ::std::string const& v =
        o.user_name_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.user_name_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.user_name_value,
        size,
        is_null,
        v);
      i.user_name_null = is_null;
      i.user_name_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.user_name_value.capacity ());
    }

    // user_passwd_
    //
    {
      ::std::string const& v =
        o.user_passwd_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.user_passwd_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.user_passwd_value,
        size,
        is_null,
        v);
      i.user_passwd_null = is_null;
      i.user_passwd_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.user_passwd_value.capacity ());
    }

    // user_nickName_
    //
    {
      ::std::string const& v =
        o.user_nickName_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.user_nickName_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.user_nickName_value,
        size,
        is_null,
        v);
      i.user_nickName_null = is_null;
      i.user_nickName_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.user_nickName_value.capacity ());
    }

    // faceType_
    //
    {
      ::int32_t const& v =
        o.faceType_;

      bool is_null (false);
      mysql::value_traits<
          ::int32_t,
          mysql::id_long >::set_image (
        i.faceType_value, is_null, v);
      i.faceType_null = is_null;
    }

    // customface_
    //
    {
      ::std::string const& v =
        o.customface_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.customface_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.customface_value,
        size,
        is_null,
        v);
      i.customface_null = is_null;
      i.customface_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.customface_value.capacity ());
    }

    // customFaceFomt_
    //
    {
      ::std::string const& v =
        o.customFaceFomt_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.customFaceFomt_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.customFaceFomt_value,
        size,
        is_null,
        v);
      i.customFaceFomt_null = is_null;
      i.customFaceFomt_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.customFaceFomt_value.capacity ());
    }

    // gender_
    //
    {
      bool const& v =
        o.gender_;

      bool is_null (false);
      mysql::value_traits<
          bool,
          mysql::id_tiny >::set_image (
        i.gender_value, is_null, v);
      i.gender_null = is_null;
    }

    // birthday_
    //
    {
      ::ttime_t const& v =
        o.birthday_;

      bool is_null (false);
      mysql::value_traits<
          ::ttime_t,
          mysql::id_ulonglong >::set_image (
        i.birthday_value, is_null, v);
      i.birthday_null = is_null;
    }

    // signature_
    //
    {
      ::std::string const& v =
        o.signature_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.signature_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.signature_value,
        size,
        is_null,
        v);
      i.signature_null = is_null;
      i.signature_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.signature_value.capacity ());
    }

    // address_
    //
    {
      ::std::string const& v =
        o.address_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.address_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.address_value,
        size,
        is_null,
        v);
      i.address_null = is_null;
      i.address_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.address_value.capacity ());
    }

    // phoneNum_
    //
    {
      ::std::string const& v =
        o.phoneNum_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.phoneNum_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.phoneNum_value,
        size,
        is_null,
        v);
      i.phoneNum_null = is_null;
      i.phoneNum_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.phoneNum_value.capacity ());
    }

    // email_
    //
    {
      ::std::string const& v =
        o.email_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.email_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.email_value,
        size,
        is_null,
        v);
      i.email_null = is_null;
      i.email_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.email_value.capacity ());
    }

    // registTime_
    //
    {
      ::ttime_t const& v =
        o.registTime_;

      bool is_null (false);
      mysql::value_traits<
          ::ttime_t,
          mysql::id_ulonglong >::set_image (
        i.registTime_value, is_null, v);
      i.registTime_null = is_null;
    }

    // remark_
    //
    {
      ::std::string const& v =
        o.remark_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.remark_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.remark_value,
        size,
        is_null,
        v);
      i.remark_null = is_null;
      i.remark_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.remark_value.capacity ());
    }

    // updateTime_
    //
    {
      ::ttime_t const& v =
        o.updateTime_;

      bool is_null (false);
      mysql::value_traits<
          ::ttime_t,
          mysql::id_ulonglong >::set_image (
        i.updateTime_value, is_null, v);
      i.updateTime_null = is_null;
    }

    // teamInfo_
    //
    {
      ::std::string const& v =
        o.teamInfo_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.teamInfo_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.teamInfo_value,
        size,
        is_null,
        v);
      i.teamInfo_null = is_null;
      i.teamInfo_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.teamInfo_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::User, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // tid_
    //
    {
      ::tid_t& v =
        o.tid_;

      mysql::value_traits<
          ::tid_t,
          mysql::id_ulonglong >::set_value (
        v,
        i.tid_value,
        i.tid_null);
    }

    // user_name_
    //
    {
      ::std::string& v =
        o.user_name_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.user_name_value,
        i.user_name_size,
        i.user_name_null);
    }

    // user_passwd_
    //
    {
      ::std::string& v =
        o.user_passwd_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.user_passwd_value,
        i.user_passwd_size,
        i.user_passwd_null);
    }

    // user_nickName_
    //
    {
      ::std::string& v =
        o.user_nickName_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.user_nickName_value,
        i.user_nickName_size,
        i.user_nickName_null);
    }

    // faceType_
    //
    {
      ::int32_t& v =
        o.faceType_;

      mysql::value_traits<
          ::int32_t,
          mysql::id_long >::set_value (
        v,
        i.faceType_value,
        i.faceType_null);
    }

    // customface_
    //
    {
      ::std::string& v =
        o.customface_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.customface_value,
        i.customface_size,
        i.customface_null);
    }

    // customFaceFomt_
    //
    {
      ::std::string& v =
        o.customFaceFomt_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.customFaceFomt_value,
        i.customFaceFomt_size,
        i.customFaceFomt_null);
    }

    // gender_
    //
    {
      bool& v =
        o.gender_;

      mysql::value_traits<
          bool,
          mysql::id_tiny >::set_value (
        v,
        i.gender_value,
        i.gender_null);
    }

    // birthday_
    //
    {
      ::ttime_t& v =
        o.birthday_;

      mysql::value_traits<
          ::ttime_t,
          mysql::id_ulonglong >::set_value (
        v,
        i.birthday_value,
        i.birthday_null);
    }

    // signature_
    //
    {
      ::std::string& v =
        o.signature_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.signature_value,
        i.signature_size,
        i.signature_null);
    }

    // address_
    //
    {
      ::std::string& v =
        o.address_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.address_value,
        i.address_size,
        i.address_null);
    }

    // phoneNum_
    //
    {
      ::std::string& v =
        o.phoneNum_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.phoneNum_value,
        i.phoneNum_size,
        i.phoneNum_null);
    }

    // email_
    //
    {
      ::std::string& v =
        o.email_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.email_value,
        i.email_size,
        i.email_null);
    }

    // registTime_
    //
    {
      ::ttime_t& v =
        o.registTime_;

      mysql::value_traits<
          ::ttime_t,
          mysql::id_ulonglong >::set_value (
        v,
        i.registTime_value,
        i.registTime_null);
    }

    // remark_
    //
    {
      ::std::string& v =
        o.remark_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.remark_value,
        i.remark_size,
        i.remark_null);
    }

    // updateTime_
    //
    {
      ::ttime_t& v =
        o.updateTime_;

      mysql::value_traits<
          ::ttime_t,
          mysql::id_ulonglong >::set_value (
        v,
        i.updateTime_value,
        i.updateTime_null);
    }

    // teamInfo_
    //
    {
      ::std::string& v =
        o.teamInfo_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.teamInfo_value,
        i.teamInfo_size,
        i.teamInfo_null);
    }
  }

  void access::object_traits_impl< ::User, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          ::tid_t,
          mysql::id_ulonglong >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::User, id_mysql >::persist_statement[] =
  "INSERT INTO `User` "
  "(`tid`, "
  "`user_name`, "
  "`user_passwd`, "
  "`user_nickName`, "
  "`faceType`, "
  "`customface`, "
  "`customFaceFomt`, "
  "`gender`, "
  "`birthday`, "
  "`signature`, "
  "`address`, "
  "`phoneNum`, "
  "`email`, "
  "`registTime`, "
  "`remark`, "
  "`updateTime`, "
  "`teamInfo`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::User, id_mysql >::find_statement[] =
  "SELECT "
  "`User`.`tid`, "
  "`User`.`user_name`, "
  "`User`.`user_passwd`, "
  "`User`.`user_nickName`, "
  "`User`.`faceType`, "
  "`User`.`customface`, "
  "`User`.`customFaceFomt`, "
  "`User`.`gender`, "
  "`User`.`birthday`, "
  "`User`.`signature`, "
  "`User`.`address`, "
  "`User`.`phoneNum`, "
  "`User`.`email`, "
  "`User`.`registTime`, "
  "`User`.`remark`, "
  "`User`.`updateTime`, "
  "`User`.`teamInfo` "
  "FROM `User` "
  "WHERE `User`.`tid`=?";

  const char access::object_traits_impl< ::User, id_mysql >::update_statement[] =
  "UPDATE `User` "
  "SET "
  "`user_name`=?, "
  "`user_passwd`=?, "
  "`user_nickName`=?, "
  "`faceType`=?, "
  "`customface`=?, "
  "`customFaceFomt`=?, "
  "`gender`=?, "
  "`birthday`=?, "
  "`signature`=?, "
  "`address`=?, "
  "`phoneNum`=?, "
  "`email`=?, "
  "`registTime`=?, "
  "`remark`=?, "
  "`updateTime`=?, "
  "`teamInfo`=? "
  "WHERE `tid`=?";

  const char access::object_traits_impl< ::User, id_mysql >::erase_statement[] =
  "DELETE FROM `User` "
  "WHERE `tid`=?";

  const char access::object_traits_impl< ::User, id_mysql >::query_statement[] =
  "SELECT "
  "`User`.`tid`, "
  "`User`.`user_name`, "
  "`User`.`user_passwd`, "
  "`User`.`user_nickName`, "
  "`User`.`faceType`, "
  "`User`.`customface`, "
  "`User`.`customFaceFomt`, "
  "`User`.`gender`, "
  "`User`.`birthday`, "
  "`User`.`signature`, "
  "`User`.`address`, "
  "`User`.`phoneNum`, "
  "`User`.`email`, "
  "`User`.`registTime`, "
  "`User`.`remark`, "
  "`User`.`updateTime`, "
  "`User`.`teamInfo` "
  "FROM `User`";

  const char access::object_traits_impl< ::User, id_mysql >::erase_query_statement[] =
  "DELETE FROM `User`";

  const char access::object_traits_impl< ::User, id_mysql >::table_name[] =
  "`User`";

  void access::object_traits_impl< ::User, id_mysql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.tid_value = 0;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.tid_ = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::User, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.tid_);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::User, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (db);

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::User, id_mysql >::pointer_type
  access::object_traits_impl< ::User, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::User, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::User, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.tid_);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::User, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::User, id_mysql >::object_type >
  access::object_traits_impl< ::User, id_mysql >::
  query (database&, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::User, id_mysql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS `User`");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE `User` (\n"
                      "  `tid` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,\n"
                      "  `user_name` TEXT NOT NULL,\n"
                      "  `user_passwd` TEXT NOT NULL,\n"
                      "  `user_nickName` TEXT NOT NULL,\n"
                      "  `faceType` INT NOT NULL,\n"
                      "  `customface` TEXT NOT NULL,\n"
                      "  `customFaceFomt` TEXT NOT NULL,\n"
                      "  `gender` TINYINT(1) NOT NULL,\n"
                      "  `birthday` BIGINT UNSIGNED NOT NULL,\n"
                      "  `signature` TEXT NOT NULL,\n"
                      "  `address` TEXT NOT NULL,\n"
                      "  `phoneNum` TEXT NOT NULL,\n"
                      "  `email` TEXT NOT NULL,\n"
                      "  `registTime` BIGINT UNSIGNED NOT NULL,\n"
                      "  `remark` TEXT NOT NULL,\n"
                      "  `updateTime` BIGINT UNSIGNED NOT NULL,\n"
                      "  `teamInfo` TEXT NOT NULL)\n"
                      " ENGINE=InnoDB");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_mysql,
    "User",
    &create_schema);
}

#include <odb/post.hxx>
